#!/bin/bash
#program:
#       This is shows the user's choice
# 2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH

echo "the script name is  ====> $0"
echo "total parameter number is ===> $#"
if [ "$#" -lt 2 ] ; then 
		echo "the number of parameter is less than 2. stop here."
        exit 0
fi
echo "your whole parameter is ===> '$@'"
echo "the lst parameter  ==> $1"
echo "the lst parameter  ==> $2"

shift #first shift

echo "total parameter number is ===> $#"
echo "your whole parameter is ==> $@"
