#!/bin/bash
#program:
#      this is only accepts the flowing parameter : one two or three 
# 2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH

echo "this program will print your selection! "
#read -p "input your choice : " choice
#case $choice in 
case $1 in
		"one")
				echo "your choice is ONE"
				;;
		"two")
				echo "your choice is TWO"
				;;
		"three")
		        echo "your choice is THREE"
				;;
		*)
				echo "Usage $0 {one|two|three}" 
				;;
esac
