#!/bin/bash
#program:
#      use loop to calculate "1+2+3+...+100" result  
# 2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH

s=0
i=0
while [ "$i" != "100" ]
do 
		i=$(($i+1))
		s=$(($s+$i))
done
echo "the result of '1+2+3+...+100=' is ==> $s"
