#!/bin/bash
#program:
#      try do calculate 1+2+...+${your input}  
# 2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH

read -p "please input a number Iw will count for 1+2+....+you input: " nu
s=0
for (( i=1; i<=$nu; i++ ))
do
		s=$(( $s+$i ))
done
echo "the result of '1+2+...+$nu=' $s"
