#!/bin/bash
#program:
#       you input your demobilization date , I calculate how many days before you demobilize.
#2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH

echo "this program will try to calculate: "
echo "how many days before you demobilazation date... "
read -p "please input your demobilization date (YYYYMMDD ex>20150316): " date2
date_d=$(echo $date2 | grep "[0-9]\{8\}")

if [ "$date_d" == "" ] ; then 
		echo "you input the wrong date format..."
		exit 1
fi

declare -i date_dem=`date -d "$date2" +%s`
declare -i date_now=`date +%s`
declare -i date_total_s=$(($date_dem-$date_now))
declare -i date_d=$(($date_total_s/60/60/24))

if [ "$date_total_s" -lt "0" ]; then
		echo "you had been demobilization before: " $((-1*$date_d)) " ago"
else
		declare -i date_h=$(($(($date_total_s-$date_d*60*60*24))/60/60))
		echo "you will demobilize after $date_d days and $date_h hours."
fi

