#!/bin/bash
#program:
#      using for ...loop to check system's infomation  
# 2015.3.16 zxl 

PATH=$PATH:~/bin
export PATH
i=0
users=$(cut -d ':' -f1 /etc/passwd)
for username in $users
do 
		i=$(($i+1))
		echo "the $i account is $username"
done
